name = "MasterThesis"
uuid = "3f366a4b-31db-490c-9e66-a1521b4fc8bd"
version = "1.0.0-DEV"
authors = ["'AnettTh' <'anett.thomassen@uit.no'> and contributors"]

[deps]
AURORA = "4b0706e8-6e74-4116-ab4c-be5c58cc7d1d"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
AURORA = "0.8.0"
CairoMakie = "0.15.13"
LinearAlgebra = "1.12.0"
NCDatasets = "0.14.15"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
